### ISSUE TITLE
No elif output? & speech format?

### ISSUE THREAD

**Issue by Daniyaldehleh** [alexa/skill-sample-python-fact-in-skill-purchases#9]
Hi All!
In line [699 ](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L699) it doesn't mention what to be returned if elif ...?

and also its written 
```
speech=("Thanks for your interest in {}.  "
                              "Would you like another random fact?".format(
                                  product[0].name))
```
isn't that not a right way to output a text an instead you should say something like:
` return handler_input.response_builder.speak()
`
Also I am not sure why line 162 & 163 has parentheses?
also is line [918](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L918) comma on purpose or mistake?

**Comment by Daniyaldehleh** [comment]
lastly, this project uses ask-cli v1. However, everything is v2 now. Is there a way to upgrade the skill to v2?

**Comment by nikhilym** [comment]
> In line 699 it doesn't mention what to be returned if elif ...?

Hey @danieldhz , you are in-fact right that one need to use `handler_input.response_builder.speak()` to set the speech responses on the alexa response. However, [Line 699](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L696-L699)'s condition is part of a longer [`if-else` loop](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L681-L726) , and is mainly for setting up the `speech` and `reprompt` variables. Once the processing is done, the response is sent [here](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L727-L732). Hope that clarifies your first question.

> Also I am not sure why line 162 & 163 has parentheses?

The parentheses on [these lines](https://github.com/alexa/skill-sample-python-fact-in-skill-purchases/blob/feb-updates/lambda/py/lambda_function.py#L162-L163) are purely for splitting the condition, so that the written python code follows the suggested line length in [PEP 008](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) style guide. Without the parentheses, one would need to add a backslash in the code and it might look ugly.

> also is line 918 comma on purpose or mistake?

I don't think it makes a difference. Do you find the code to fail with that comma present? 

> lastly, this project uses ask-cli v1. However, everything is v2 now. Is there a way to upgrade the skill to v2?

At the time this skill sample was written, there was no ASK CLI v2. You should be able to follow the [migration guide](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html) to convert this to a v2 project. If you are interested, please send out a PR for this sample with the structure migrated to v2 CLI and we will be happy to review. Thanks.

Closing this issue. Please let us know if you still have problems.
